version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: EST
  open-pull-requests-limit: 10
  reviewers:
  - ryelo
  allow:
  - dependency-name: "@redhat-cloud-services/frontend*"
  - dependency-name: "@patternfly/*"
    dependency-type: direct
  ignore:
  - dependency-name: "@patternfly/react-core"
    versions:
    - 4.101.3
    - 4.106.1
    - 4.106.2
    - 4.115.1
    - 4.90.2
    - 4.97.0
    - 4.97.1
    - 4.97.2
  - dependency-name: "@redhat-cloud-services/frontend-components"
    versions:
    - 3.0.1
    - 3.0.10
    - 3.0.11
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.0.9
    - 3.1.0
    - 3.1.1
    - 3.1.10
    - 3.1.2
    - 3.1.3
    - 3.1.4
    - 3.1.5
    - 3.1.6
    - 3.1.7
    - 3.1.9
  - dependency-name: "@patternfly/patternfly"
    versions:
    - 4.102.1
    - 4.80.3
    - 4.87.2
    - 4.87.3
    - 4.90.5
    - 4.96.2
  - dependency-name: "@patternfly/react-table"
    versions:
    - 4.20.15
    - 4.23.0
    - 4.23.1
    - 4.23.14
    - 4.23.2
    - 4.24.0
    - 4.24.1
    - 4.26.6
  - dependency-name: "@redhat-cloud-services/frontend-components-utilities"
    versions:
    - 3.0.2
    - 3.0.3
    - 3.1.0
    - 3.1.1
  - dependency-name: "@redhat-cloud-services/frontend-components-charts"
    versions:
    - 2.4.3
    - 3.0.0
    - 3.0.1
